name: projectadopet
description: "A Flutter project for dog adoption."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/orange_dog.png
    - assets/blue_dog.png
    - assets/red_dog.png
    - assets/yellow_dog.png
    - assets/white_dog.png
    - assets/owner.png
