// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRGQM8NjZvCOVDQ9vACqhVZk7R-S0sZk4',
    appId: '1:49737244385:web:f8e4a97fa06b1e698d61a0',
    messagingSenderId: '49737244385',
    projectId: 'adopetfirebase-2d14c',
    authDomain: 'adopetfirebase-2d14c.firebaseapp.com',
    storageBucket: 'adopetfirebase-2d14c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYqJiZ5VB-zDDhha-RboAmPVFwsqEGRO0',
    appId: '1:49737244385:android:e0800d9e91c382068d61a0',
    messagingSenderId: '49737244385',
    projectId: 'adopetfirebase-2d14c',
    storageBucket: 'adopetfirebase-2d14c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRGQM8NjZvCOVDQ9vACqhVZk7R-S0sZk4',
    appId: '1:49737244385:web:a276f5694ba84c288d61a0',
    messagingSenderId: '49737244385',
    projectId: 'adopetfirebase-2d14c',
    authDomain: 'adopetfirebase-2d14c.firebaseapp.com',
    storageBucket: 'adopetfirebase-2d14c.firebasestorage.app',
  );
}
